/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.bivi.browser.calendar;

import java.awt.BorderLayout;
import javax.swing.tree.TreeSelectionModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import se.trixon.bivi.core.BiviGlobals;
import se.trixon.bivi.core.BiviTopComponent;
import se.trixon.bivi.db.api.DbMonitor;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//se.trixon.bivi.browser.calendar//CalendarBrowser//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CalendarBrowserTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "se.trixon.bivi.browser.calendar.CalendarBrowserTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Browse", position = 2),
    @ActionReference(path = "Shortcuts", name = "D-3")
})
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CalendarBrowserAction",
        preferredID = "CalendarBrowserTopComponent"
)
public final class CalendarBrowserTopComponent extends BiviTopComponent implements ExplorerManager.Provider, DbMonitor.DbEvent {
    private final ExplorerManager mExplorerManager = BiviGlobals.getAlbumExplorerManager();
    private BeanTreeView mBeanTreeView;

    public CalendarBrowserTopComponent() {
        mBundle = NbBundle.getBundle(getClass());
        initComponents();
        setName(mBundle.getString("CTL_CalendarBrowserTopComponent"));
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);

        init();
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mExplorerManager;
    }

    @Override
    public void onDbChanged() {
        populate();
    }

    @Override
    public void onDbRootAlbumsChanged() {
        populate();
    }

    private void init() {
        associateLookup(ExplorerUtils.createLookup(BiviGlobals.getCalendarExplorerManager(), getActionMap()));
        mBeanTreeView = new BeanTreeView();
        mBeanTreeView.setRootVisible(false);
        mBeanTreeView.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        add(mBeanTreeView, BorderLayout.CENTER);
        DbMonitor.INSTANCE.add(this);
        populate();
    }
    private void populate() {
//        Children albumRoot = Children.create(new AlbumRootChildFactory(), true);
//        Node rootNode = new AbstractNode(albumRoot);
//        rootNode.setDisplayName(getName());
//        mExplorerManager.setRootContext(rootNode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
