/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.bivi.db;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.DialogDescriptor;
import org.openide.NotificationLineSupport;
import org.openide.util.NbBundle;
import se.trixon.almond.dialogs.FileChooserPanel;
import se.trixon.almond.dictionary.Dict;
import se.trixon.bivi.db.api.DbManager;

/**
 *
 * @author Patrik Karlsson
 */
public class DbSelectPanel extends javax.swing.JPanel {

    private DialogDescriptor mDialogDescriptor;
    private NotificationLineSupport mNotificationLineSupport;
    private static final DbManager mDbManager = DbManager.INSTANCE;

    /**
     * Creates new form DbSelectPanel
     */
    public DbSelectPanel() {
        initComponents();
        init();
    }

    String getPath() {
        return dirChooserPanel.getPath();
    }

    void setDialogDescriptor(DialogDescriptor dialogDescriptor) {
        mNotificationLineSupport = dialogDescriptor.createNotificationLineSupport();
        mDialogDescriptor = dialogDescriptor;

        validateInput();
    }

    private void init() {
        DocumentListener documentListener = new DocumentListener() {

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateInput();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                validateInput();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateInput();
            }
        };

        dirChooserPanel.setPath(mDbManager.getPath());
        dirChooserPanel.getTextField().getDocument().addDocumentListener(documentListener);
        dirChooserPanel.setDropMode(FileChooserPanel.DropMode.SINGLE);
        dirChooserPanel.setMode(JFileChooser.DIRECTORIES_ONLY);
    }

    private void validateInput() {
        File dir = new File(dirChooserPanel.getPath());
        File dbFile = new File(dir, mDbManager.getDbFilename());
        boolean valid = dir.isDirectory();
        if (valid) {
            if (dbFile.exists()) {
                mNotificationLineSupport.setInformationMessage(NbBundle.getMessage(getClass(),"DbFileFound"));
            } else {
                mNotificationLineSupport.setWarningMessage(NbBundle.getMessage(getClass(),"DbFileNotFound"));
            }
        } else {
            mNotificationLineSupport.setErrorMessage(Dict.INVALID_DIRECTORY.getString());
        }
        mDialogDescriptor.setValid(valid);
    }
    private DbManager INSTANCE;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirChooserPanel = new se.trixon.almond.dialogs.FileChooserPanel();

        dirChooserPanel.setHeader(org.openide.util.NbBundle.getMessage(DbSelectPanel.class, "DbSelectPanel.dirChooserPanel.header")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirChooserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.almond.dialogs.FileChooserPanel dirChooserPanel;
    // End of variables declaration//GEN-END:variables
}
