/*
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.bivi.core.windows.statusbar;

import java.awt.Component;
import org.netbeans.modules.progress.spi.Controller;
import org.openide.awt.StatusLineElementProvider;
import se.trixon.almond.icon.Pict;

/**
 *
 * @author Patrik Karlsson
 */
//@ServiceProvider(service = StatusLineElementProvider.class)
public class StatusBar extends javax.swing.JPanel implements StatusLineElementProvider {

    private static final int ICON_SIZE = 18;

    /**
     * Creates new form ZoomPanel
     */
    public StatusBar() {
        initComponents();

        revertFilterButton.setIcon(Pict.Actions.DOCUMENT_REVERT.get(ICON_SIZE));
        configFilterButton.setIcon(Pict.Actions.VIEW_FILTER.get(ICON_SIZE));
        fitButton.setIcon(Pict.Actions.ZOOM_FIT_BEST.get(ICON_SIZE));
        fullButton.setIcon(Pict.Actions.ZOOM_ORIGINAL.get(ICON_SIZE));
        outButton.setIcon(Pict.Actions.ZOOM_OUT.get(ICON_SIZE));
        inButton.setIcon(Pict.Actions.ZOOM_IN.get(ICON_SIZE));

        progressPanel.add(Controller.getDefault().getVisualComponent());
    }

    @Override
    public Component getStatusLineElement() {
        return this;
    }

    public void setText(String text) {
        label.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label = new javax.swing.JLabel();
        progressPanel = new javax.swing.JPanel();
        filterToolBar = new javax.swing.JToolBar();
        revertFilterButton = new javax.swing.JButton();
        configFilterButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        zoomToolBar = new javax.swing.JToolBar();
        fitButton = new javax.swing.JButton();
        fullButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        inButton = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        label.setBackground(new java.awt.Color(255, 153, 153));
        label.setFont(label.getFont().deriveFont(label.getFont().getSize()+3f));
        org.openide.awt.Mnemonics.setLocalizedText(label, org.openide.util.NbBundle.getMessage(StatusBar.class, "StatusBar.label.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        add(label, gridBagConstraints);

        progressPanel.setLayout(new javax.swing.BoxLayout(progressPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(progressPanel, new java.awt.GridBagConstraints());

        filterToolBar.setFloatable(false);
        filterToolBar.setRollover(true);
        filterToolBar.setBorderPainted(false);

        revertFilterButton.setFocusable(false);
        revertFilterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        revertFilterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        filterToolBar.add(revertFilterButton);

        configFilterButton.setFocusable(false);
        configFilterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        configFilterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        filterToolBar.add(configFilterButton);

        jTextField1.setEditable(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 27));
        filterToolBar.add(jTextField1);

        add(filterToolBar, new java.awt.GridBagConstraints());

        zoomToolBar.setFloatable(false);
        zoomToolBar.setBorderPainted(false);

        fitButton.setFocusable(false);
        fitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitButtonActionPerformed(evt);
            }
        });
        zoomToolBar.add(fitButton);

        fullButton.setFocusable(false);
        fullButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fullButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomToolBar.add(fullButton);

        outButton.setFocusable(false);
        outButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        outButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomToolBar.add(outButton);

        slider.setPreferredSize(new java.awt.Dimension(120, 21));
        zoomToolBar.add(slider);

        inButton.setFocusable(false);
        inButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomToolBar.add(inButton);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100%" }));
        zoomToolBar.add(comboBox);

        add(zoomToolBar, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void fitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitButtonActionPerformed
    }//GEN-LAST:event_fitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox;
    private javax.swing.JButton configFilterButton;
    private javax.swing.JToolBar filterToolBar;
    private javax.swing.JButton fitButton;
    private javax.swing.JButton fullButton;
    private javax.swing.JButton inButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    private javax.swing.JButton outButton;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JButton revertFilterButton;
    private javax.swing.JSlider slider;
    private javax.swing.JToolBar zoomToolBar;
    // End of variables declaration//GEN-END:variables
}
